---
- name: Copy Ansible Server Public Key to Target Servers
  hosts: all
  become: yes

  tasks:
    - name: Ensure the SSH directory exists
      file:
        path: "/root/.ssh/"
        state: directory
        mode: "0700"

    - name: Copy Ansible server public key to authorized_keys
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: make direcotry
    file:
      path: "/home/root/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/root/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/root/.ssh/authorized_keys"
      line: "{{ pubkey }}"
