- name: Copying the /root/.ssh/id_rsa.pub to new inventiory hosts
  hosts: all
  become: yes

  tasks: 
    - name: copy the publickey from source file to destinaltion path
      copy:
        src: id_rsa.pub
        dest: /root/.ssh/authorized_keys
      notify: Restart ssh

  handlers: 
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
