---
- name: Update and Upgrade Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages in ubuntu server
      apt:
        upgrade: yes
