- name: Install HAProxy on ubuntu servers
  hosts: haproxy_inventory
  become: yes
  
  tasks:
    - name: Update apt cache repository 
      apt:
        update_cache: yes

    - name: Install HAProxy on servers and start the service 
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration file from haproxy.conf.j2 to /etc/haproxy/haproxy.cfg
      copy:
        src: haproxy.conf.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy
      become: yes
- name: check apache is installed  on backend server
  hosts: backend_server
  become: yes
  tasks:
    - name: check if apache is installed or not
      stat: 
        path: /usr/sbin/apache2
      register: apache_installed
      become: yes
    
    - name: Install Apachec if not installed 
      apt:
        name: apache2 
        state: present
      when: "'backend_server' in group_names and apache_installed.stat.exists == false"
            
    - name: Copy Apache configurtaion file from apache.conf.j2 to /etc/apache2/apache2.conf 
      copy: 
        src: apache.conf.j2
        dest: /etc/apache2/apache2.conf
      notify: Restart Apache
      when: "'backend_server' in group_names"

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
        enabled: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        enabled: yes

    - name: Debug Inventory
      debug:
        msg: "Group names: {{ groups.keys() }}"  


