---
- name: Install NTP and Configure on ubuntu servers
  hosts: all
  become: yes
  vars: 
   ntp_server1: ntp.workernode1.com
   ntp_server2: ntp.workernode2.com
  tasks:
   - name: remove chrony on NTP servers its recommended to remove chrony on NTP servers to avaiod issues
     apt: chrony
     state: absent
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install NTP and start the service 
      apt:
        name: ntp
        state: present

    - name: Configure NTP servers
      template:
        src:  ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: Restart NTP

  handlers:
    - name: Restart NTP
      service:
        name: ntp
        state: restarted
        enabled: yes
